spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

logging:
  structured:
    format: ecs

app:
  stripe:
    api-key: ${STRIPE_API_KEY}
  email:
    from: ${RESEND_FROM_EMAIL}
    resend:
      api-key: ${RESEND_API_KEY}
management:
  tracing:
    sampling:
      probability: 0.1
  Zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "health,Prometheus"
  metrics:
    export:
      Prometheus:
        enabled: true