apiVersion: v1
kind: ConfigMap
metadata:
  name: sports-backend-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://postgres-service:5432/sportly"
  DB_USERNAME: "postgres"
  RESEND_FROM_EMAIL: "onboarding@resend.dev"
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-backend-deployment
  labels:
    app: sports-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sports-platform
  template:
    metadata:
      labels:
        app: sports-platform
    spec:
      containers:
        - name: backend
          image: ghcr.io/chuuch/sports-platform-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: sports-backend-config
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: sports-backend-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sports-backend-config
                  key: DB_USERNAME
            - name: RESEND_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: sports-backend-config
                  key: RESEND_FROM_EMAIL
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: sports-backend-config
                  key: ZIPKIN_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resend-secret
                  key: RESEND_API_KEY
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: sports-backend-service
spec:
  type: ClusterIP
  selector:
    app: sports-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080